export const PAYOUTS_ACTION_TYPES = {
  FETCH_PAYOUTS_START: "payouts/FETCH_PAYOUTS_START",
  FETCH_PAYOUTS_SUCCESS: "payouts/FETCH_PAYOUTS_SUCCESS",
  FETCH_PAYOUTS_FAILED: "payouts/FETCH_PAYOUTS_FAILED",
  SET_PAYOUTS_FILTER: "payouts/SET_PAYOUTS_FILTER",
  SET_PAYOUTS_IS_FILTER_CHANGED: "payouts/SET_PAYOUTS_IS_FILTER_CHANGED",
  SET_PAYOUTS_PAGE: "payouts/SET_PAYOUTS_PAGE",
  SET_PAYOUTS_ITEMS_PER_PAGE: "payouts/SET_PAYOUTS_ITEMS_PER_PAGE",
  SET_PAYOUTS_IS_ITEMS_PER_PAGE_CHANGED: "payouts/SET_PAYOUTS_IS_ITEMS_PER_PAGE_CHANGED",
  CLEAR_PAYOUTS: "payouts/CLEAR_PAYOUTS"
};
